version = 0.1

[default.build.parameters]
template_file = "infra/sam/template.yaml"
use_container = true

[default.deploy.parameters]
template_file = ".aws-sam/build/template.yaml"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
resolve_s3 = true
